version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    volumes:
      - ./server.properties:/etc/kafka/server.properties
    networks:
      - kafka-network

  kafka-manager:
    image: 'hlebalbau/kafka-manager:latest'
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - '9000:9000'
    depends_on:
      - kafka
    networks:
      - kafka-network

#Não é necessário usar o kafka ui, porque o quarkus tem uma DEV UI no modo de desenvolvimento
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#      - DYNAMIC_CONFIG_ENABLED=true
#    ports:
#      - "8080:8080"
#    networks:
#      - kafka-network

networks:
  kafka-network:
    driver: bridge
